// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJdB-SLaVsRBPyuzhKy6OHp-opd6YUT00',
    appId: '1:397799843551:android:dd34f4e7ffc481e8482b6a',
    messagingSenderId: '397799843551',
    projectId: 'spotify-bloc-flutter',
    storageBucket: 'spotify-bloc-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWvj3J69pbbLXrKezS-SBswBvY-bOz6lw',
    appId: '1:397799843551:ios:455e6d27f07c6fe7482b6a',
    messagingSenderId: '397799843551',
    projectId: 'spotify-bloc-flutter',
    storageBucket: 'spotify-bloc-flutter.firebasestorage.app',
    iosBundleId: 'com.example.spotifyBloc',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDOWO3kPAa-Py-7W9CV6Q-PiY_4iEkU-rc",
    authDomain: "spotify-bloc-flutter.firebaseapp.com",
    projectId: "spotify-bloc-flutter",
    storageBucket: "spotify-bloc-flutter.firebasestorage.app",
    messagingSenderId: "397799843551",
    appId: "1:397799843551:web:7ce9d4c44badc55e482b6a",
  );
}
